# Generated by Django 4.1.3 on 2022-12-26 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='fechaInicio',
            field=models.DateField(default='2022-11-11'),
        ),
    ]
